package com.aymen.todolist.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

import java.sql.Timestamp;

@Entity(name = "tasks")
public class Task {

    // Unique identifier for the task, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false)
    private Long task_id;

    // Description of the task, cannot be null
    @Column(nullable = false)
    private String task_description;

    // Indicates whether the task is complete or not
    @Column(nullable = false)
    private boolean complete;

    // Timestamp when the task was created, automatically set by Hibernate
    @Temporal(TemporalType.TIMESTAMP)
    @CreationTimestamp
    @Column(updatable = false, nullable = false)
    private Timestamp created_at;

    // Default constructor
    public Task() {
    }

    // Constructor with parameters for creating a task
    public Task(Long taskId, String taskDescription, boolean complete, Timestamp createdAt) {
        this.task_id = taskId;
        this.task_description = taskDescription;
        this.complete = complete;
        this.created_at = createdAt;
    }

    // Getter and setter methods for each attribute

    public Long getTaskId() {
        return task_id;
    }

    public void setTaskId(Long taskId) {
        this.task_id = taskId;
    }

    public String getTaskDescription() {
        return task_description;
    }

    public void setTaskDescription(String taskDescription) {
        this.task_description = taskDescription;
    }

    public boolean getComplete() {
        return complete;
    }

    public void setComplete(boolean complete) {
        this.complete = complete;
    }

    public Timestamp getCreatedAt() {
        return created_at;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.created_at = createdAt;
    }

    @Override
    public String toString() {
        return "Task{" +
                "taskId=" + task_id +
                ", taskDescription='" + task_description + '\'' +
                ", isComplete=" + complete +
                ", createdAt=" + created_at +
                '}';
    }
}
